In [1]:
import pandas as pd
import numpy as np

In [2]:
zf = pd.read_excel('/home/ryan/stark/machinehack/Food_QUalityA_ParticipantsData/Food_QUalityA_ParticipantsData/Data_Train.xlsx')

In [3]:
test = pd.read_excel('/home/ryan/stark/machinehack/Food_QUalityA_ParticipantsData/Food_QUalityA_ParticipantsData/Data_Test.xlsx')

In [4]:
from sklearn import preprocessing 
  
# label_encoder object knows how to understand word labels. 
label_encoder = preprocessing.LabelEncoder() 
test['Type']= label_encoder.fit_transform(test['Type']) 
test['Geo_Loc'] = label_encoder.fit_transform(df['Geo_Loc'])

NameError: name 'df' is not defined

In [ ]:
cols_to_drop = [
    'LicenseNo',
    'Date',
    'FacilityID',
    'FacilityName',
    'ID'
    ]

zf = zf.drop(cols_to_drop, axis=1)
test = test.drop(cols_to_drop, axis=1)

In [ ]:
total = zf.isnull().sum().sort_values(ascending=False)
percent_1 = zf.isnull().sum()/zf.isnull().count()*100
percent_2 = (np.round(percent_1, 1)).sort_values(ascending=False)
missing_data = pd.concat([total, percent_2], axis=1, keys=['Total', '%']) #ptr
missing_data

In [ ]:
total = test.isnull().sum().sort_values(ascending=False)
percent_1 = test.isnull().sum()/test.isnull().count()*100
percent_2 = (np.round(percent_1, 1)).sort_values(ascending=False)
missing_data = pd.concat([total, percent_2], axis=1, keys=['Total', '%']) #ptr
missing_data

In [ ]:
testf=test.copy()

In [ ]:
df = zf.copy()

In [ ]:
from sklearn.impute import SimpleImputer
imp = SimpleImputer(strategy='most_frequent')
df = imp.fit_transform(df)
testf = imp.fit_transform(testf)

In [ ]:
dataframe = pd.DataFrame.from_records(df)

In [ ]:
dataframetest = pd.DataFrame.from_records(testf)

In [ ]:
dataframetest.head()

In [ ]:
dataframetest.rename(columns = {0:'Type',1:'Street',2:'City',3:'State',4:'LocationID',5:'Reason',6:'SectionViolations',7:'RiskLevel',8:'Geo_Loc',9:'Inspection_Results'},inplace=True)
dataframe.rename(columns = {0:'Type',1:'Street',2:'City',3:'State',4:'LocationID',5:'Reason',6:'SectionViolations',7:'RiskLevel',8:'Geo_Loc',9:'Inspection_Results'},inplace=True)

In [ ]:
dataframetest.head()

In [ ]:
dataframe.head(3)

In [ ]:
dataframetest.to_excel(excel_writer = "/home/ryan/stark/machinehack/Food_QUalityA_ParticipantsData/Food_QUalityA_ParticipantsData/Data_TestCLEANED.xlsx")
dataframe.to_excel(excel_writer = "/home/ryan/stark/machinehack/Food_QUalityA_ParticipantsData/Food_QUalityA_ParticipantsData/Data_TrainCLEANED.xlsx")

In [5]:
df = pd.read_excel('/home/ryan/stark/machinehack/Food_QUalityA_ParticipantsData/Food_QUalityA_ParticipantsData/Data_TrainCLEANED.xlsx')

In [6]:
test = pd.read_excel("/home/ryan/stark/machinehack/Food_QUalityA_ParticipantsData/Food_QUalityA_ParticipantsData/Data_TestCLEANED.xlsx")

In [7]:
df.head(3)

,Type,Street,City,State,LocationID,Reason,SectionViolations,RiskLevel,Geo_Loc,Inspection_Results
0,RESTAURANT,15522,id-11235901,id_1890134,81876,CANVASS,33,High,locid16406,4
1,GROCERY STORE,3057,id-11235901,id_1890134,81862,COMPLAINT,33,High,locid878,4
2,RESTAURANT,14988,id-11235901,id_1890134,81883,CANVASS,32,High,locid3368,6

In [8]:
test['Type'].describe()

count          49148
unique           301
top       RESTAURANT
freq           34051
Name: Type, dtype: object

In [9]:
test.head(3)

,Type,Street,City,State,LocationID,Reason,SectionViolations,RiskLevel,Geo_Loc
0,GROCERY STORE,17352,id-11235901,id_1890134,81864,CANVASS,19,Low,locid1145
1,SCHOOL,15536,id-11235901,id_1890134,81871,CANVASS,32,High,locid16450
2,RESTAURANT,8849,id-11235901,id_1890134,81902,CANVASS,32,High,locid12916

In [10]:
df = pd.get_dummies(df, prefix="RiskLevel",columns=['RiskLevel'])
df = pd.get_dummies(df, prefix="City",columns=['City'])
df = pd.get_dummies(df, prefix="State",columns=['State'])
df = pd.get_dummies(df, prefix="Reason",columns=['Reason'])
#df = pd.get_dummies(df, prefix="SectionViolations",columns=['SectionViolations'])

In [11]:
test = pd.get_dummies(test, prefix="RiskLevel",columns=['RiskLevel'])
test = pd.get_dummies(test, prefix="City",columns=['City'])
test = pd.get_dummies(test, prefix="State",columns=['State'])
test = pd.get_dummies(test, prefix="Reason",columns=['Reason'])
#df = pd.get_dummies(df, prefix="SectionViolations",columns=['SectionViolations'])

In [12]:
test.head()

,Type,Street,LocationID,SectionViolations,Geo_Loc,RiskLevel_High,RiskLevel_Low,RiskLevel_Medium,RiskLevel_Uncertain,City_id-11235901,...,Reason_LICENSE RE-INSPECTION,Reason_LICENSE-TASK FORCE,Reason_OUT OF BUSINESS,Reason_RECENT INSPECTION,Reason_SHORT FORM COMPLAINT,Reason_SHORT FORM FIRE-COMPLAINT,Reason_SUSPECTED FOOD POISONING,Reason_SUSPECTED FOOD POISONING RE-INSPECTION,Reason_TAG REMOVAL,Reason_TASK FORCE LIQUOR 1475
0,GROCERY STORE,17352,81864,19,locid1145,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,SCHOOL,15536,81871,32,locid16450,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,RESTAURANT,8849,81902,32,locid12916,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,SCHOOL,11663,81869,32,locid7292,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,RESTAURANT,16286,81874,32,locid2048,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [13]:
df

,Type,Street,LocationID,SectionViolations,Geo_Loc,Inspection_Results,RiskLevel_High,RiskLevel_Low,RiskLevel_Medium,RiskLevel_Uncertain,...,Reason_LICENSE RE-INSPECTION,Reason_LICENSE-TASK FORCE,Reason_OUT OF BUSINESS,Reason_RECENT INSPECTION,Reason_SHORT FORM COMPLAINT,Reason_SHORT FORM FIRE-COMPLAINT,Reason_SUSPECTED FOOD POISONING,Reason_SUSPECTED FOOD POISONING RE-INSPECTION,Reason_TAG REMOVAL,Reason_TASK FORCE LIQUOR 1475
0,RESTAURANT,15522,81876,33,locid16406,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,GROCERY STORE,3057,81862,33,locid878,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,RESTAURANT,14988,81883,32,locid3368,6,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,RESTAURANT,3661,81859,31,locid11839,4,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,RESTAURANT,7876,81886,30,locid12264,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,RESTAURANT,12275,81877,18,locid3935,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,RESTAURANT,2133,81887,32,locid8876,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,RESTAURANT,5006,81851,32,locid7586,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
8,CHILDREN'S SERVICES FACILITY,4554,81892,32,locid10595,4,1,0,0,0,...,1,0,0,0,0,0,0,0,0,0
9,RESTAURANT,5899,81877,32,locid4082,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,RESTAURANT,16017,81864,32,locid1408,6,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
11,GROCERY STORE,4538,81867,33,locid8797,4,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0
12,RESTAURANT,17881,81862,32,locid735,3,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,RESTAURANT,14317,81905,16,locid15780,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,RESTAURANT,4306,81846,2,locid7773,5,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,GAS STATION,16864,81866,32,locid3190,4,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
16,RESTAURANT,12997,81901,33,locid15243,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,RESTAURANT,4998,81851,18,locid6907,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,RESTAURANT,16901,81897,21,locid1451,5,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,GROCERY STORE,13485,81885,32,locid15481,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
20,RESTAURANT,8060,81861,32,locid4676,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,RESTAURANT,17137,81902,32,locid12146,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,SCHOOL,11623,81877,33,locid4246,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,PALETERIA,13866,81884,32,locid11671,4,1,0,0,0,...,1,0,0,0,0,0,0,0,0,0
24,DAYCARE ABOVE AND UNDER 2 YEARS,4632,81873,32,locid243,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,MEAT PACKING,17161,81852,32,locid7754,4,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
26,GROCERY STORE,16529,81857,11,locid8770,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
27,RESTAURANT,12567,81875,33,locid15037,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,SCHOOL,15092,81904,34,locid16065,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,LONG TERM CARE,11988,81854,32,locid4052,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147413,SCHOOL,11623,81877,32,locid4246,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
147414,DAYCARE COMBO 1586,16773,81897,31,locid1527,4,1,0,0,0,...,1,0,0,0,0,0,0,0,0,0
147415,SCHOOL,13261,81857,40,locid8293,5,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
147416,RESTAURANT,11730,81870,23,locid14320,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
147417,RESTAURANT,16980,81864,30,locid1465,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
147418,RESTAURANT,10443,81856,32,locid8201,6,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
147419,GROCERY STORE,11277,81886,18,locid13964,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
147420,RESTAURANT,12001,81877,3,locid4016,5,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
147421,RESTAURANT,11595,81874,10,locid2742,1,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0
147422,GROCERY STORE,15759,81882,41,locid2377,4,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
147423,RESTAURANT,13766,81852,32,locid6672,3,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
147424,RESTAURANT,12583,81875,32,locid14623,6,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
147425,RESTAURANT,1196,81855,51,locid9565,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
147426,RESTAURANT,12500,81906,18,locid7295,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
147427,RESTAURANT,9431,81863,32,locid12491,6,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
147428,RESTAURANT,91,81854,32,locid4666,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
147429,RESTAURANT,6397,81894,29,locid2052,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
147430,RESTAURANT,5254,81855,30,locid8970,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
147431,SCHOOL,9995,81863,38,locid13399,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
147432,RESTAURANT,130,81867,33,locid10162,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
147433,MOBILE PREPARED FOOD VENDOR,12524,81854,32,locid3886,4,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
147434,RESTAURANT,11356,81870,30,locid14111,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
147435,BAKERY,11326,81886,32,locid14000,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
147436,RESTAURANT,16667,81865,33,locid1677,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
147437,SCHOOL,1031,81873,14,locid221,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
147438,GROCERY STORE,6229,81873,3,locid203,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
147439,RESTAURANT,3697,81848,32,locid7202,4,1,0,0,0,...,0,0,0,0,1,0,0,0,0,0
147440,RESTAURANT,13027,81877,32,locid3614,6,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
147441,RESTAURANT,17833,81888,3,locid757,5,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
147442,CHILDREN'S SERVICES FACILITY,7750,81904,32,locid16090,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [14]:
from sklearn import preprocessing 
  
# label_encoder object knows how to understand word labels. 
label_encoder = preprocessing.LabelEncoder() 
  
# Encode labels in column 'species'. 
df['Type']= label_encoder.fit_transform(df['Type']) 
df['Geo_Loc'] = label_encoder.fit_transform(df['Geo_Loc'])

test['Type']= label_encoder.fit_transform(test['Type']) 
test['Geo_Loc'] = label_encoder.fit_transform(test['Geo_Loc'])

In [15]:
df.head()

,Type,Street,LocationID,SectionViolations,Geo_Loc,Inspection_Results,RiskLevel_High,RiskLevel_Low,RiskLevel_Medium,RiskLevel_Uncertain,...,Reason_LICENSE RE-INSPECTION,Reason_LICENSE-TASK FORCE,Reason_OUT OF BUSINESS,Reason_RECENT INSPECTION,Reason_SHORT FORM COMPLAINT,Reason_SHORT FORM FIRE-COMPLAINT,Reason_SUSPECTED FOOD POISONING,Reason_SUSPECTED FOOD POISONING RE-INSPECTION,Reason_TAG REMOVAL,Reason_TASK FORCE LIQUOR 1475
0,326,15522,81876,33,6889,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,182,3057,81862,33,14998,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,326,14988,81883,32,9140,6,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,326,3661,81859,31,1991,4,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,326,7876,81886,30,2443,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,326,12275,81877,18,9758,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,326,2133,81887,32,15101,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,326,5006,81851,32,13704,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
8,75,4554,81892,32,642,4,1,0,0,0,...,1,0,0,0,0,0,0,0,0,0
9,326,5899,81877,32,9916,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,326,16017,81864,32,4407,6,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
11,182,4538,81867,33,15016,4,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0
12,326,17881,81862,32,13448,3,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,326,14317,81905,16,6217,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,326,4306,81846,2,13903,5,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,162,16864,81866,32,8946,4,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
16,326,12997,81901,33,5645,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,326,4998,81851,18,12964,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,326,16901,81897,21,4864,5,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,182,13485,81885,32,5897,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
20,326,8060,81861,32,10555,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,326,17137,81902,32,2319,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,351,11623,81877,33,10089,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,297,13866,81884,32,1812,4,1,0,0,0,...,1,0,0,0,0,0,0,0,0,0
24,125,4632,81873,32,8136,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,258,17161,81852,32,13882,4,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
26,182,16529,81857,11,14988,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
27,326,12567,81875,33,5428,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,351,15092,81904,34,6527,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,251,11988,81854,32,9883,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147413,351,11623,81877,32,10089,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
147414,127,16773,81897,31,5673,4,1,0,0,0,...,1,0,0,0,0,0,0,0,0,0
147415,351,13261,81857,40,14470,5,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
147416,326,11730,81870,23,4667,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
147417,326,16980,81864,30,5013,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
147418,326,10443,81856,32,14370,6,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
147419,182,11277,81886,18,4281,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
147420,326,12001,81877,3,9847,5,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
147421,326,11595,81874,10,8469,1,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0
147422,182,15759,81882,41,8080,4,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
147423,326,13766,81852,32,12709,3,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
147424,326,12583,81875,32,4986,6,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
147425,326,1196,81855,51,15848,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
147426,326,12500,81906,18,13387,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
147427,326,9431,81863,32,2683,6,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
147428,326,91,81854,32,10544,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
147429,326,6397,81894,29,7731,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
147430,326,5254,81855,30,15205,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
147431,351,9995,81863,38,3670,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
147432,326,130,81867,33,180,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
147433,274,12524,81854,32,9704,4,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
147434,326,11356,81870,30,4440,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
147435,26,11326,81886,32,4323,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
147436,326,16667,81865,33,7287,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
147437,351,1031,81873,14,7900,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
147438,182,6229,81873,3,7707,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
147439,326,3697,81848,32,13286,4,1,0,0,0,...,0,0,0,0,1,0,0,0,0,0
147440,326,13027,81877,32,9408,6,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
147441,326,17833,81888,3,13688,5,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
147442,75,7750,81904,32,6555,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [16]:
df.to_excel(excel_writer = "/home/ryan/stark/machinehack/Food_QUalityA_ParticipantsData/Food_QUalityA_ParticipantsData/Data_TrainCLEANEDandONEHOT1.xlsx")
test.to_excel(excel_writer = "/home/ryan/stark/machinehack/Food_QUalityA_ParticipantsData/Food_QUalityA_ParticipantsData/Data_TestCLEANEDandONEHOT1.xlsx")

In [17]:
df = pd.read_excel("/home/ryan/stark/machinehack/Food_QUalityA_ParticipantsData/Food_QUalityA_ParticipantsData/Data_TrainCLEANEDandONEHOT1.xlsx")
test = pd.read_excel("/home/ryan/stark/machinehack/Food_QUalityA_ParticipantsData/Food_QUalityA_ParticipantsData/Data_TestCLEANEDandONEHOT1.xlsx")

In [18]:
df.head()

,Type,Street,LocationID,SectionViolations,Geo_Loc,Inspection_Results,RiskLevel_High,RiskLevel_Low,RiskLevel_Medium,RiskLevel_Uncertain,...,Reason_LICENSE RE-INSPECTION,Reason_LICENSE-TASK FORCE,Reason_OUT OF BUSINESS,Reason_RECENT INSPECTION,Reason_SHORT FORM COMPLAINT,Reason_SHORT FORM FIRE-COMPLAINT,Reason_SUSPECTED FOOD POISONING,Reason_SUSPECTED FOOD POISONING RE-INSPECTION,Reason_TAG REMOVAL,Reason_TASK FORCE LIQUOR 1475
0,326,15522,81876,33,6889,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,182,3057,81862,33,14998,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,326,14988,81883,32,9140,6,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,326,3661,81859,31,1991,4,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,326,7876,81886,30,2443,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [19]:
test.head()

,Type,Street,LocationID,SectionViolations,Geo_Loc,RiskLevel_High,RiskLevel_Low,RiskLevel_Medium,RiskLevel_Uncertain,City_id-11235901,...,Reason_LICENSE RE-INSPECTION,Reason_LICENSE-TASK FORCE,Reason_OUT OF BUSINESS,Reason_RECENT INSPECTION,Reason_SHORT FORM COMPLAINT,Reason_SHORT FORM FIRE-COMPLAINT,Reason_SUSPECTED FOOD POISONING,Reason_SUSPECTED FOOD POISONING RE-INSPECTION,Reason_TAG REMOVAL,Reason_TASK FORCE LIQUOR 1475
0,127,17352,81864,19,1341,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,256,15536,81871,32,5812,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,234,8849,81902,32,2658,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,256,11663,81869,32,11144,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,234,16286,81874,32,6425,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0