In [1]:
import pandas as pd
import numpy as np

In [46]:
zf = pd.read_excel('//home/ryan/stark/machinehack/Food_QUalityA_ParticipantsData/Food_QUalityA_ParticipantsData/Data_Train.xlsx')

,ID,Date,LicenseNo,FacilityID,FacilityName,Type,Street,City,State,LocationID,Reason,SectionViolations,RiskLevel,Geo_Loc,Inspection_Results
0,31103489027986,26-04-2010,4744,8123,7715,RESTAURANT,15522,id-11235901,id_1890134,81876.0,CANVASS,33.0,High,locid16406,4
1,10088999935915,21-06-2009,2973,12268,11664,GROCERY STORE,3057,id-11235901,id_1890134,81862.0,COMPLAINT,33.0,High,locid878,4
2,40148966010272,01-05-2013,18223,1112,969,RESTAURANT,14988,id-11235901,id_1890134,81883.0,CANVASS,NaN,High,locid3368,6
3,37157708563676,28-09-2015,20825,20007,19115,RESTAURANT,3661,id-11235901,id_1890134,81859.0,CANVASS RE-INSPECTION,31.0,Medium,locid11839,4
4,47478049564374,09-12-2015,2136,16867,10409,RESTAURANT,7876,id-11235901,id_1890134,81886.0,COMPLAINT,30.0,High,locid12264,4
5,25234292966802,07-02-2016,13009,7942,7547,RESTAURANT,12275,id-11235901,id_1890134,81877.0,CANVASS,18.0,High,locid3935,1
6,17640167351232,04-04-2011,9621,3791,3576,RESTAURANT,2133,id-11235901,id_1890134,81887.0,CANVASS RE-INSPECTION,32.0,High,locid8876,4
7,46787129696096,16-07-2018,32170,24054,8766,RESTAURANT,5006,id-11235901,id_1890134,81851.0,LICENSE,NaN,Low,locid7586,1
8,34878549916037,11-08-2015,27027,24785,23652,CHILDREN'S SERVICES FACILITY,4554,id-11235901,id_1890134,81892.0,LICENSE RE-INSPECTION,NaN,High,locid10595,4
9,21318229935335,23-04-2012,7131,2892,2707,RESTAURANT,5899,id-11235901,id_1890134,81877.0,CANVASS,32.0,High,locid4082,4
10,10214985518889,07-12-2014,26522,5574,5307,RESTAURANT,16017,id-11235901,id_1890134,81864.0,CANVASS,NaN,Medium,locid1408,6
11,44211502136202,31-07-2016,3350,12919,12263,GROCERY STORE,4538,id-11235901,id_1890134,81867.0,SUSPECTED FOOD POISONING,33.0,High,locid8797,4
12,48584696239023,19-10-2016,15323,2017,1829,RESTAURANT,17881,id-11235901,id_1890134,81862.0,CANVASS,NaN,High,locid735,3
13,10962644430544,07-01-2014,34228,24693,23563,RESTAURANT,14317,id-11235901,id_1890134,81905.0,CANVASS,16.0,High,locid15780,1
14,26337396850533,08-12-2014,37390,26965,5722,RESTAURANT,4306,id-11235901,id_1890134,81846.0,COMPLAINT,2.0,High,locid7773,5
15,48866457037333,29-08-2010,5661,1286,1142,GAS STATION,16864,id-11235901,id_1890134,81866.0,COMPLAINT,32.0,Low,locid3190,4
16,23828335222981,06-09-2012,15738,1211,1064,RESTAURANT,12997,id-11235901,id_1890134,81901.0,CANVASS,33.0,High,locid15243,4
17,25384990615031,30-06-2015,35333,22105,21130,RESTAURANT,4998,id-11235901,id_1890134,81851.0,CANVASS,18.0,High,locid6907,1
18,47262805952874,11-04-2013,19661,2137,1947,RESTAURANT,16901,id-11235901,id_1890134,81897.0,CANVASS,21.0,High,locid1451,5
19,21734770657261,29-07-2010,14430,26262,25054,GROCERY STORE,13485,id-11235901,id_1890134,81885.0,LICENSE,NaN,Low,locid15481,1
20,34579588311235,18-06-2013,14111,5317,4581,RESTAURANT,8060,id-11235901,id_1890134,81861.0,CANVASS,32.0,High,locid4676,4
21,39169509740871,31-07-2016,4787,922,19345,RESTAURANT,17137,id-11235901,id_1890134,81902.0,COMPLAINT,32.0,High,locid12146,4
22,37988386300108,10-02-2016,11675,5795,5525,SCHOOL,11623,id-11235901,id_1890134,81877.0,CANVASS,33.0,High,locid4246,4
23,40746553558670,08-08-2010,15236,18438,17611,PALETERIA,13866,id-11235901,id_1890134,81884.0,LICENSE RE-INSPECTION,NaN,High,locid11671,4
24,27539983663744,21-08-2016,23283,20715,19810,DAYCARE ABOVE AND UNDER 2 YEARS,4632,id-11235901,id_1890134,81873.0,LICENSE,32.0,High,locid243,4
25,11856211428900,24-12-2011,2853,10222,9698,MEAT PACKING,17161,id-11235901,id_1890134,81852.0,CANVASS,NaN,Medium,locid7754,4
26,35474878472249,18-05-2015,3476,8680,8225,GROCERY STORE,16529,id-11235901,id_1890134,81857.0,COMPLAINT,11.0,Medium,locid8770,1
27,35469423818787,07-09-2015,21448,9538,9862,RESTAURANT,12567,id-11235901,id_1890134,81875.0,CANVASS RE-INSPECTION,33.0,High,locid15037,4
28,23403031350901,26-04-2015,0,15121,5604,SCHOOL,15092,id-11235901,id_1890134,81904.0,CANVASS,34.0,High,locid16065,4
29,33644571625014,01-03-2015,25070,17398,16616,LONG TERM CARE,11988,id-11235901,id_1890134,81854.0,COMPLAINT,NaN,High,locid4052,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147413,23347959434399,18-05-2014,11675,5795,5525,SCHOOL,11623,id-11235901,id_1890134,81877.0,CANVASS,32.0,High,locid4246,4
147414,35772856380557,11-10-2010,2075,19156,18306,DAYCARE COMBO 1586,16773,id-11235901,id_1890134,81897.0,LICENSE RE-INSPECTION,31.0,High,locid1527,4
147415,49382614134892,13-11-2012,19330,26565,25337,SCHOOL,13261,id-11235901,id_1890134,81857.0,CONSULTATION,40.0,High,locid8293,5
147416,20139702531897,24-09-2018,37162,24205,23088,RESTAURANT,11730,id-11235901,id_1890134,81870.0,CANVASS,23.0,High,locid14320,4
147417,19421954800167,06-07-2010,8314,4225,4019,RESTAURANT,16980,id-11235901,id_1890134,81864.0,COMPLAINT RE-INSPECTION,30.0,High,locid1465,4
147418,22114566297124,23-07-2009,2606,23249,22180,NaN,10443,id-11235901,id_1890134,81856.0,CANVASS,NaN,High,locid8201,6
147419,27031790055932,20-01-2009,4805,8101,7698,GROCERY STORE,11277,id-11235901,id_1890134,81886.0,COMPLAINT,18.0,Medium,locid13964,1
147420,15585185010452,02-08-2018,14949,22897,21868,RESTAURANT,12001,id-11235901,id_1890134,81877.0,COMPLAINT,3.0,High,locid4016,5
147421,27024602452871,17-09-2018,5517,25902,24741,RESTAURANT,11595,id-11235901,id_1890134,81874.0,SUSPECTED FOOD POISONING,10.0,High,locid2742,1
147422,32148502267748,16-04-2013,35142,582,470,GROCERY STORE,15759,id-11235901,id_1890134,81882.0,COMPLAINT,41.0,Low,locid2377,4
147423,49201243810583,24-10-2017,15560,17041,16265,RESTAURANT,13766,id-11235901,id_1890134,81852.0,CANVASS,NaN,High,locid6672,3
147424,20715625143040,04-10-2009,1303,19326,18465,NaN,12583,id-11235901,id_1890134,81875.0,CANVASS,NaN,Low,locid14623,6
147425,45717395572203,12-03-2018,133,5303,5048,RESTAURANT,1196,id-11235901,id_1890134,81855.0,CANVASS,51.0,High,locid9565,1
147426,34003151715677,07-06-2012,7777,25574,23087,RESTAURANT,12500,id-11235901,id_1890134,81906.0,CANVASS,18.0,High,locid7295,1
147427,20839120602786,08-01-2014,20820,448,326,RESTAURANT,9431,id-11235901,id_1890134,81863.0,CANVASS,NaN,Medium,locid12491,6
147428,22931478719161,09-06-2015,24570,1592,1438,RESTAURANT,91,id-11235901,id_1890134,81854.0,LICENSE,NaN,High,locid4666,1
147429,21621235199585,10-05-2012,36151,13479,12816,RESTAURANT,6397,id-11235901,id_1890134,81894.0,CANVASS,29.0,High,locid2052,1
147430,37748794606466,20-01-2010,5888,22802,21776,RESTAURANT,5254,id-11235901,id_1890134,81855.0,CANVASS,30.0,High,locid8970,4
147431,19516716381429,06-05-2013,10861,4956,3621,SCHOOL,9995,id-11235901,id_1890134,81863.0,CANVASS,38.0,High,locid13399,4
147432,22317707931588,11-05-2017,2938,5944,5685,RESTAURANT,130,id-11235901,id_1890134,81867.0,CANVASS,33.0,High,locid10162,4
147433,26131065472559,12-04-2017,26717,27079,25846,MOBILE PREPARED FOOD VENDOR,12524,id-11235901,id_1890134,81854.0,LICENSE,NaN,Low,locid3886,4
147434,20445320482526,30-05-2013,5588,26550,25324,RESTAURANT,11356,id-11235901,id_1890134,81870.0,CANVASS,30.0,High,locid14111,4
147435,11282139945113,16-11-2016,10983,18491,17662,BAKERY,11326,id-11235901,id_1890134,81886.0,CANVASS,32.0,High,locid14000,4
147436,21161647203676,09-12-2013,17143,22155,21175,RESTAURANT,16667,id-11235901,id_1890134,81865.0,COMPLAINT,33.0,High,locid1677,4
147437,10693486771979,30-01-2012,19450,10552,10022,SCHOOL,1031,id-11235901,id_1890134,81873.0,CANVASS RE-INSPECTION,14.0,High,locid221,1
147438,32616888047244,15-06-2015,23001,19617,18736,GROCERY STORE,6229,id-11235901,id_1890134,81873.0,COMPLAINT,3.0,Medium,locid203,1
147439,38335234403261,28-11-2010,35329,21729,20760,RESTAURANT,3697,id-11235901,id_1890134,81848.0,SHORT FORM COMPLAINT,NaN,High,locid7202,4
147440,42693381689429,23-09-2014,5361,12685,12038,RESTAURANT,13027,id-11235901,id_1890134,81877.0,CANVASS,NaN,Medium,locid3614,6
147441,49087006944080,25-01-2018,12338,10898,10324,RESTAURANT,17833,id-11235901,id_1890134,81888.0,CANVASS RE-INSPECTION,3.0,High,locid757,5
147442,16714564150129,14-02-2012,18743,1392,1249,CHILDREN'S SERVICES FACILITY,7750,id-11235901,id_1890134,81904.0,LICENSE,32.0,High,locid16090,4

array([[u'RESTAURANT', 15522, u'id-11235901', ..., u'High',
        u'locid16406', 4],
       [u'GROCERY STORE', 3057, u'id-11235901', ..., u'High',
        u'locid878', 4],
       [u'RESTAURANT', 14988, u'id-11235901', ..., u'High', u'locid3368',
        6],
       ...,
       [u'RESTAURANT', 13027, u'id-11235901', ..., u'Medium',
        u'locid3614', 6],
       [u'RESTAURANT', 17833, u'id-11235901', ..., u'High', u'locid757',
        5],
       [u"CHILDREN'S SERVICES FACILITY", 7750, u'id-11235901', ...,
        u'High', u'locid16090', 4]], dtype=object)

In [38]:
cols_to_drop = [
    'LicenseNo',
    'Date',
    'FacilityID',
    'FacilityName',
    'ID'
    ]

zf = zf.drop(cols_to_drop, axis=1)
zf.head()

,Type,Street,City,State,LocationID,Reason,SectionViolations,RiskLevel,Geo_Loc,Inspection_Results
0,RESTAURANT,15522,id-11235901,id_1890134,81876.0,CANVASS,33.0,High,locid16406,4
1,GROCERY STORE,3057,id-11235901,id_1890134,81862.0,COMPLAINT,33.0,High,locid878,4
2,RESTAURANT,14988,id-11235901,id_1890134,81883.0,CANVASS,NaN,High,locid3368,6
3,RESTAURANT,3661,id-11235901,id_1890134,81859.0,CANVASS RE-INSPECTION,31.0,Medium,locid11839,4
4,RESTAURANT,7876,id-11235901,id_1890134,81886.0,COMPLAINT,30.0,High,locid12264,4

In [9]:
total = zf.isnull().sum().sort_values(ascending=False)
percent_1 = zf.isnull().sum()/zf.isnull().count()*100
percent_2 = (np.round(percent_1, 1)).sort_values(ascending=False)
missing_data = pd.concat([total, percent_2], axis=1, keys=['Total', '%']) #ptr
missing_data

/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  after removing the cwd from sys.path.

                    Total     %
City                    0   0.0
Geo_Loc                 0   0.0
Inspection_Results      0   0.0
LocationID             35   0.0
Reason                  0   0.0
RiskLevel               0   0.0
SectionViolations   39068  26.5
State                   0   0.0
Street                  0   0.0
Type                 3485   2.4

AttributeError: 'numpy.ndarray' object has no attribute 'isnull'

In [ ]:
df = zf.copy()

In [19]:
from sklearn.impute import SimpleImputer
imp = SimpleImputer(strategy='most_frequent')
df = imp.fit_transform(df)

In [51]:
dataframe = pd.DataFrame.from_records(df)

In [52]:
dataframe.head()

,0,1,2,3,4,5,6,7,8,9
0,RESTAURANT,15522,id-11235901,id_1890134,81876.0,CANVASS,33.0,High,locid16406,4
1,GROCERY STORE,3057,id-11235901,id_1890134,81862.0,COMPLAINT,33.0,High,locid878,4
2,RESTAURANT,14988,id-11235901,id_1890134,81883.0,CANVASS,32.0,High,locid3368,6
3,RESTAURANT,3661,id-11235901,id_1890134,81859.0,CANVASS RE-INSPECTION,31.0,Medium,locid11839,4
4,RESTAURANT,7876,id-11235901,id_1890134,81886.0,COMPLAINT,30.0,High,locid12264,4

In [53]:
dataframe.rename(columns = {0:'Type',1:'Street',2:'City',3:'State',4:'LocationID',5:'Reason',6:'SectionViolations',7:'RiskLevel',8:'Geo_Loc',9:'Inspection_Results'},inplace=True)

In [54]:
dataframe.head()

,Type,Street,City,State,LocationID,Reason,SectionViolations,RiskLevel,Geo_Loc,Inspection_Results
0,RESTAURANT,15522,id-11235901,id_1890134,81876.0,CANVASS,33.0,High,locid16406,4
1,GROCERY STORE,3057,id-11235901,id_1890134,81862.0,COMPLAINT,33.0,High,locid878,4
2,RESTAURANT,14988,id-11235901,id_1890134,81883.0,CANVASS,32.0,High,locid3368,6
3,RESTAURANT,3661,id-11235901,id_1890134,81859.0,CANVASS RE-INSPECTION,31.0,Medium,locid11839,4
4,RESTAURANT,7876,id-11235901,id_1890134,81886.0,COMPLAINT,30.0,High,locid12264,4
5,RESTAURANT,12275,id-11235901,id_1890134,81877.0,CANVASS,18.0,High,locid3935,1
6,RESTAURANT,2133,id-11235901,id_1890134,81887.0,CANVASS RE-INSPECTION,32.0,High,locid8876,4
7,RESTAURANT,5006,id-11235901,id_1890134,81851.0,LICENSE,32.0,Low,locid7586,1
8,CHILDREN'S SERVICES FACILITY,4554,id-11235901,id_1890134,81892.0,LICENSE RE-INSPECTION,32.0,High,locid10595,4
9,RESTAURANT,5899,id-11235901,id_1890134,81877.0,CANVASS,32.0,High,locid4082,4
10,RESTAURANT,16017,id-11235901,id_1890134,81864.0,CANVASS,32.0,Medium,locid1408,6
11,GROCERY STORE,4538,id-11235901,id_1890134,81867.0,SUSPECTED FOOD POISONING,33.0,High,locid8797,4
12,RESTAURANT,17881,id-11235901,id_1890134,81862.0,CANVASS,32.0,High,locid735,3
13,RESTAURANT,14317,id-11235901,id_1890134,81905.0,CANVASS,16.0,High,locid15780,1
14,RESTAURANT,4306,id-11235901,id_1890134,81846.0,COMPLAINT,2.0,High,locid7773,5
15,GAS STATION,16864,id-11235901,id_1890134,81866.0,COMPLAINT,32.0,Low,locid3190,4
16,RESTAURANT,12997,id-11235901,id_1890134,81901.0,CANVASS,33.0,High,locid15243,4
17,RESTAURANT,4998,id-11235901,id_1890134,81851.0,CANVASS,18.0,High,locid6907,1
18,RESTAURANT,16901,id-11235901,id_1890134,81897.0,CANVASS,21.0,High,locid1451,5
19,GROCERY STORE,13485,id-11235901,id_1890134,81885.0,LICENSE,32.0,Low,locid15481,1
20,RESTAURANT,8060,id-11235901,id_1890134,81861.0,CANVASS,32.0,High,locid4676,4
21,RESTAURANT,17137,id-11235901,id_1890134,81902.0,COMPLAINT,32.0,High,locid12146,4
22,SCHOOL,11623,id-11235901,id_1890134,81877.0,CANVASS,33.0,High,locid4246,4
23,PALETERIA,13866,id-11235901,id_1890134,81884.0,LICENSE RE-INSPECTION,32.0,High,locid11671,4
24,DAYCARE ABOVE AND UNDER 2 YEARS,4632,id-11235901,id_1890134,81873.0,LICENSE,32.0,High,locid243,4
25,MEAT PACKING,17161,id-11235901,id_1890134,81852.0,CANVASS,32.0,Medium,locid7754,4
26,GROCERY STORE,16529,id-11235901,id_1890134,81857.0,COMPLAINT,11.0,Medium,locid8770,1
27,RESTAURANT,12567,id-11235901,id_1890134,81875.0,CANVASS RE-INSPECTION,33.0,High,locid15037,4
28,SCHOOL,15092,id-11235901,id_1890134,81904.0,CANVASS,34.0,High,locid16065,4
29,LONG TERM CARE,11988,id-11235901,id_1890134,81854.0,COMPLAINT,32.0,High,locid4052,4
...,...,...,...,...,...,...,...,...,...,...
147413,SCHOOL,11623,id-11235901,id_1890134,81877.0,CANVASS,32.0,High,locid4246,4
147414,DAYCARE COMBO 1586,16773,id-11235901,id_1890134,81897.0,LICENSE RE-INSPECTION,31.0,High,locid1527,4
147415,SCHOOL,13261,id-11235901,id_1890134,81857.0,CONSULTATION,40.0,High,locid8293,5
147416,RESTAURANT,11730,id-11235901,id_1890134,81870.0,CANVASS,23.0,High,locid14320,4
147417,RESTAURANT,16980,id-11235901,id_1890134,81864.0,COMPLAINT RE-INSPECTION,30.0,High,locid1465,4
147418,RESTAURANT,10443,id-11235901,id_1890134,81856.0,CANVASS,32.0,High,locid8201,6
147419,GROCERY STORE,11277,id-11235901,id_1890134,81886.0,COMPLAINT,18.0,Medium,locid13964,1
147420,RESTAURANT,12001,id-11235901,id_1890134,81877.0,COMPLAINT,3.0,High,locid4016,5
147421,RESTAURANT,11595,id-11235901,id_1890134,81874.0,SUSPECTED FOOD POISONING,10.0,High,locid2742,1
147422,GROCERY STORE,15759,id-11235901,id_1890134,81882.0,COMPLAINT,41.0,Low,locid2377,4
147423,RESTAURANT,13766,id-11235901,id_1890134,81852.0,CANVASS,32.0,High,locid6672,3
147424,RESTAURANT,12583,id-11235901,id_1890134,81875.0,CANVASS,32.0,Low,locid14623,6
147425,RESTAURANT,1196,id-11235901,id_1890134,81855.0,CANVASS,51.0,High,locid9565,1
147426,RESTAURANT,12500,id-11235901,id_1890134,81906.0,CANVASS,18.0,High,locid7295,1
147427,RESTAURANT,9431,id-11235901,id_1890134,81863.0,CANVASS,32.0,Medium,locid12491,6
147428,RESTAURANT,91,id-11235901,id_1890134,81854.0,LICENSE,32.0,High,locid4666,1
147429,RESTAURANT,6397,id-11235901,id_1890134,81894.0,CANVASS,29.0,High,locid2052,1
147430,RESTAURANT,5254,id-11235901,id_1890134,81855.0,CANVASS,30.0,High,locid8970,4
147431,SCHOOL,9995,id-11235901,id_1890134,81863.0,CANVASS,38.0,High,locid13399,4
147432,RESTAURANT,130,id-11235901,id_1890134,81867.0,CANVASS,33.0,High,locid10162,4
147433,MOBILE PREPARED FOOD VENDOR,12524,id-11235901,id_1890134,81854.0,LICENSE,32.0,Low,locid3886,4
147434,RESTAURANT,11356,id-11235901,id_1890134,81870.0,CANVASS,30.0,High,locid14111,4
147435,BAKERY,11326,id-11235901,id_1890134,81886.0,CANVASS,32.0,High,locid14000,4
147436,RESTAURANT,16667,id-11235901,id_1890134,81865.0,COMPLAINT,33.0,High,locid1677,4
147437,SCHOOL,1031,id-11235901,id_1890134,81873.0,CANVASS RE-INSPECTION,14.0,High,locid221,1
147438,GROCERY STORE,6229,id-11235901,id_1890134,81873.0,COMPLAINT,3.0,Medium,locid203,1
147439,RESTAURANT,3697,id-11235901,id_1890134,81848.0,SHORT FORM COMPLAINT,32.0,High,locid7202,4
147440,RESTAURANT,13027,id-11235901,id_1890134,81877.0,CANVASS,32.0,Medium,locid3614,6
147441,RESTAURANT,17833,id-11235901,id_1890134,81888.0,CANVASS RE-INSPECTION,3.0,High,locid757,5
147442,CHILDREN'S SERVICES FACILITY,7750,id-11235901,id_1890134,81904.0,LICENSE,32.0,High,locid16090,4

In [58]:
#dataframe.to_excel(excel_writer = "/home/ryan/stark/machinehack/Food_QUalityA_ParticipantsData/Food_QUalityA_ParticipantsData/Data_TrainCLEANED.xlsx")

In [77]:
df = pd.read_excel('/home/ryan/stark/machinehack/Food_QUalityA_ParticipantsData/Food_QUalityA_ParticipantsData/Data_TrainCLEANED.xlsx')

In [78]:
df.head()

,Type,Street,City,State,LocationID,Reason,SectionViolations,RiskLevel,Geo_Loc,Inspection_Results
0,RESTAURANT,15522,id-11235901,id_1890134,81876,CANVASS,33,High,locid16406,4
1,GROCERY STORE,3057,id-11235901,id_1890134,81862,COMPLAINT,33,High,locid878,4
2,RESTAURANT,14988,id-11235901,id_1890134,81883,CANVASS,32,High,locid3368,6
3,RESTAURANT,3661,id-11235901,id_1890134,81859,CANVASS RE-INSPECTION,31,Medium,locid11839,4
4,RESTAURANT,7876,id-11235901,id_1890134,81886,COMPLAINT,30,High,locid12264,4

In [79]:
df['Type'].unique()

array([u'RESTAURANT', u'GROCERY STORE', u"CHILDREN'S SERVICES FACILITY",
       u'GAS STATION', u'SCHOOL', u'PALETERIA',
       u'DAYCARE ABOVE AND UNDER 2 YEARS', u'MEAT PACKING',
       u'LONG TERM CARE', u'LIQUOR', u'DAYCARE (2 - 6 YEARS)',
       u'COMMISSARY FOR SOFT SERVE ICE CREAM TRUCKS',
       u'CONVENIENCE STORE', u'DAYCARE (UNDER 2 YEARS)',
       u'SHARED KITCHEN USER (LONG TERM)', u'GOLDEN DINER', u'BAKERY',
       u'WRIGLEY ROOFTOP', u'DAYCARE COMBO 1586', u'DAYCARE NIGHT',
       u'MOBILE FOOD PREPARER', u'POPCORN SHOP', u'TAVERN', u'HOSPITAL',
       u'CATERING', u'PRIVATE SCHOOL', u'SHELTER', u'TAVERN GRILL',
       u'MOBILE FOOD DISPENSER', u'MOBILE DESSERTS VENDOR', u'WHOLESALE',
       u'SPECIAL EVENT', u'GAS STATION/RESTAURANT', u'SENIOR DAY CARE',
       u'DAYCARE', u'BANQUET', u'BANQUET HALL', u'ROOFTOPS',
       u'SHARED KITCHEN', u'LIVE POULTRY', u'BAR/GRILL',
       u'DAYCARE 2 YRS TO 12 YRS', u'RESTAURANT(PROTEIN SHAKE BAR)',
       u'COFFEE SHOP', u'MOBILE PREPARED FOOD VENDOR',
       u"1023 CHILDERN'S SERVICE FACILITY", u'KIOSK',
       u'SHARED KITCHEN USER (SHORT TERM)', u'THEATER', u'CAFETERIA',
       u'BREWPUB', u'NURSING HOME', u'CHURCH', u'GAS STATION /GROCERY',
       u'COOKING SCHOOL', u'WRIGLEY ROOF TOP', u'1023', u'CHARTER SCHOOL',
       u'SHARED KITCHEN USER (LONG TREM)', u'SHUFFLEBOARD CLUB WITH BAR',
       u'ICE CREAM PARLOR', u'SUMMER FEEDING',
       u"CHILDERN'S SERVICE FACILITY", u'RESTAURANT/BAKERY',
       u"1023 CHILDERN'S SERVICES FACILITY",
       u"1023-CHILDREN'S SERVICES FACILITY",
       u'MOBILE FROZEN DESSERTS VENDOR', u'MOVIE THEATER',
       u'GROCERY/GAS STATION', u'CONVENIENCE', u'ROOFTOP',
       u"1023 CHILDERN'S SERVICE S FACILITY", u'RESTAURANT/GROCERY STORE',
       u'POULTRY SLAUGHTER', u'RESTAURANT/BAR', u'NAVY PIER KIOSK',
       u'STADIUM', u'GROCERY& RESTAURANT', u'GROCERY/RESTAURANT',
       u'BEFORE AND AFTER SCHOOL PROGRAM', u'FITNESS CENTER',
       u'ROOF TOPS', u'UNIVERSITY CAFETERIA', u'PREP INSIDE SCHOOL',
       u'PUSHCART', u'A-NOT-FOR-PROFIT CHEF TRAINING PROGRAM',
       u'MOBILE FOOD TRUCK', u'GROCERY(SUSHI PREP)', u'ASSISTED LIVING',
       u'LIQUORE STORE/BAR', u'CULINARY SCHOOL', u'CONVENIENT STORE',
       u'GROCERY STORE/BAKERY', u'MOVIE THEATRE', u'GROCERY & RESTAURANT',
       u'HOT DOG STATION', u'DAY CARE 2-14', u'ROOF TOP',
       u'JUICE AND SALAD BAR', u'NOT-FOR-PROFIT CLUB',
       u'GROCERY/ RESTAURANT', u'HERBAL MEDICINE', u'NORTHERLY ISLAND',
       u'BAKERY/DELI', u'CANDY STORE',
       u'POP-UP ESTABLISHMENT HOST-TIER II', u'GROCERY AND BUTCHER',
       u'HOOKA LOUNGE', u'GROCERY STORE/GAS STATION',
       u'RESTAURANT.BANQUET HALLS', u'HEALTH/ JUICE BAR',
       u'GROCERY/SERVICE GAS STATION', u'TRUCK', u'WEIGHT LOSS PROGRAM',
       u'MUSIC VENUE', u'COFFEE  SHOP', u'REST/GROCERY', u'SUSHI COUNTER',
       u'CELL PHONE STORE', u'BAR', u'CANDY/GELATO', u'SOCIAL CLUB',
       u'MOBILE FOOD', u'DAYCARE (2 YEARS)', u'HOTEL', u'PUBLIC SHCOOL',
       u'RIVERWALK CAFE', u'BANQUET ROOMS', u'HERBALIFE',
       u'NOT FOR PROFIT', u'LONG-TERM CARE FACILITY', u'WAREHOUSE',
       u'COLLEGE', u'THEATER & RESTAURANT', u'DOLLAR STORE',
       u'SUPPORTIVE LIVING', u'GAS', u'REST/GYM', u'DRUG STORE',
       u'ROOM SERVICE', u'ART GALLERY W/WINE AND BEER',
       u'CHILDRENS SERVICES FACILITY', u'CHARTER SCHOOL/CAFETERIA',
       u'ICE CREAM SHOP', u'CHINESE HERBS', u'RIVERWALK',
       u'BANQUET DINING', u'NUTRITION/HERBALIFE', u'GOLF COURSE',
       u'CULINARY ARTS SCHOOL', u'EMPLOYEE KITCHEN', u'CHURCH KITCHEN',
       u'PRE PACKAGED', u'1475 LIQUOR', u'OTHER', u'COMMISSARY',
       u'BANQUET/KITCHEN', u'REGULATED BUSINESS', u'DAYCARE 2-6, UNDER 6',
       u'MOBILE FROZEN DESSERT VENDOR', u'LINITED BUSINESS',
       u'EVENT SPACE', u'LOUNGE/BANQUET HALL', u'GAS STATION/STORE',
       u'LIQUOR CONSUMPTION ON PREMISES.', u'LIQOUR BREWERY TASTING',
       u'1005 NURSING HOME', u'DAYCARE COMBO',
       u"CHILDERN'S SERVICES  FACILITY", u'COFFEE CART',
       u'LONG TERM CARE FACILITY', u'BANQUET FACILITY', u'DAY CARE 1023',
       u'BOOK STORE', u'FOOD BOOTH', u'GAS STATION/MINI MART',
       u'GROCERY/TAVERN', u'ASSISTED LIVING SENIOR CARE', u'STORE',
       u'ALTERNATIVE SCHOOL', u'DOLLAR TREE', u'TEA BREWING',
       u'GROCERY/CAFE', u'HOSTEL', u'CITY OF CHICAGO COLLEGE',
       u'MFD TRUCK', u'GYM STORE', u'HOT DOG CART',
       u'RESTAURANT/HOSPITAL', u'RESTUARANT AND BAR', u'SCHOOL CAFETERIA',
       u"O'HARE KIOSK", u'AIRPORT LOUNGE',
       u'GROCERY STORE/COOKING SCHOOL', u'CHURCH (SPECIAL EVENTS)',
       u'WINE STORE', u'RESTAURANT/GAS STATION', u'BANQUET HALL/CATERING',
       u'CHARITY AID KITCHEN', u'BUTCHER SHOP', u'FOOD VENDING MACHINES',
       u'CHURCH/SPECIAL EVENTS', u'BEVERAGE/SILVERWARE WAREHOUSE',
       u'BAKERY/RESTAURANT', u'DRUG/FOOD STORE', u'GYM',
       u'MOBILPREPARED FOOD VENDOR', u'GROCERY STORE/TAQUERIA',
       u'SOUP KITCHEN', u'PHARMACY/GROCERY', u'ADULT DAYCARE',
       u'WATERMELON HOUSE', u'DINING HALL', u'CAFE/STORE', u'SMOKEHOUSE',
       u'PASTRY SCHOOL', u'ICE CREAM', u'GROCERY(GAS STATION)',
       u'PRODUCE VENDOR', u'LOUNGE', u'RESTAURANT/GROCERY',
       u'WINE TASTING BAR', u'GAS STATION/FOOD', u'GROCERY',
       u'EVENT VENU', u'PHARMACY', u'BAKERY/ RESTAURANT', u'PANTRY',
       u'HERBAL LIFE', u'DONUT SHOP', u'CATERING/CAFE',
       u'TEACHING SCHOOL', u'HEALTH CARE STORE', u'YOUTH HOUSING',
       u'SUMMER FEEDING PREP AREA', u'NAIL SHOP', u'REST/ROOFTOP',
       u'SMOOTHIE BAR', u'GAS STATION/GROCERY', u'URBAN FARM',
       u'COFFEE KIOSK', u'CHURCH/DAY CARE', u'SUPPORTIVE LIVING FACILITY',
       u'GROCERY/DELI', u'COFFEE/TEA', u'SERVICE BAR/THEATRE',
       u'BANQUETS', u'HERABALIFE', u'TOBACCO STORE', u'SNACK SHOP',
       u'BANQUET ROOM', u'WHOLESALE BAKERY',
       u'GOLF COURSE CONNCESSION STAND', u'BREWERY', u'GROCERY/BUTCHER',
       u'TAVERN/RESTAURANT', u'GROCERY STORE/ RESTAURANT',
       u'TENT RSTAURANT', u'NEWSSTAND', u'GROCERY/BAKERY', u'VIDEO STORE',
       u'BOWLING LANES/BANQUETS', u'FISH MARKET', u'POOL',
       u'TEMPORARY KIOSK', u'CULINARY CLASS ROOMS', u'THEATRE', u'CAFE',
       u'HEALTH CENTER', u'(GAS STATION)', u'RETAIL', u'PACKAGED LIQUOR',
       u'MOBILE FROZEN DESSERTS DISPENSER-NON-MOTORIZED',
       u'RETAIL FOOD/GAS STATION', u'CLOTHING STORE', u'GELATO SHOP',
       u'CHILDERN ACTIVITY FACILITY', u'CHARTER SCHOOL CAFETERIA',
       u'SLAUGHTER HOUSE/ GROCERY', u'HERBALCAL',
       u'GAS STATION/CONVENIENCE STORE', u'MOBIL FOOD 1315',
       u'AFTER SCHOOL PROGRAM', u'PUSH CARTS', u'DISTRIBUTION CENTER',
       u'HERBAL DRINKS', u'15 MONTS TO 5 YEARS OLD',
       u'HIGH SCHOOL KITCHEN', u'CANDY SHOP', u'REPACKAGING PLANT',
       u'GAS STATION STORE', u'GAS STATION/ GROCERY STORE', u'JUICE BAR',
       u'GAS STATION /SUBWAY MINI MART.', u'COFFEE VENDING MACHINE',
       u'MEXICAN CANDY STORE', u'GROCERY STORE /PHARMACY',
       u'BAKERY/GROCERY', u'CONVNIENCE STORE', u'CHURCH/SPECIAL EVENT',
       u'DRUG TREATMENT FACILITY', u'CATERED EVENTS', u'HERBAL',
       u'COMMISARY RESTAURANT', u'DISTRIBUTOR', u'NUTRITION STORE',
       u'REHAB CENTER', u'TEA STORE', u'VFW HALL', u'FRENCH MARKET SPACE',
       u'MOBILE FROZEN DESSERT DISP/NON-MOTORIZED',
       u'GROCERY/DOLLAR STORE', u'GROCERY/TAQUERIA',
       u'FROZEN DESSERT PUSHCARTS', u'EXERCISE AND NUTRITION BAR',
       u'DAY CARE', u'DRUG STORE/GROCERY',
       u'MOBILE FROZEN DESSERT DISPENSER_NON  MOTORIZED.',
       u'CUSTOM POULTRY SLAUGHTER', u'GAS STATION/STORE GROCERY',
       u'POP-UP FOOD ESTABLISHMENT USER-TIER III', u'WHOLESALE & RETAIL',
       u'CONVENIENCE/GAS STATION', u'HERBALIFE STORE',
       u"1023 CHILDREN'S SERVICES FACILITY", u'RETAIL WINE/WINE BAR',
       u'GROCERY STORE / GAS STATION', u'DAYCARE 6 WKS-5YRS',
       u'CAT/LIQUOR', u'HERBAL LIFE SHOP', u'CANDY',
       u'COLD/FROZEN FOOD STORAGE', u'NIGHT CLUB', u'GROCERY/DRUG STORE',
       u'LIQUOR STORE', u'HERBAL REMEDY', u'VENDING COMMISSARY',
       u'CAR WASH', u'COFFEE ROASTER', u'KITCHEN DEMO', u'CATERED LIQUOR',
       u'CHURCH/AFTER SCHOOL PROGRAM', u'LONG-TERM CARE',
       u'ASSISSTED LIVING', u'LIVE BUTCHER', u'RESTAURANT AND LIQUOR',
       u'CATERING AND WHOLESALE', u'ROOFTOP PATIO', u'DRUG/GROCERY STORE',
       u'DAY SPA', u'HELICOPTER TERMINAL', u'PALETERIA /ICECREAM SHOP',
       u'FITNESS STUDIO', u'DOLLAR & GROCERY STORE',
       u'DAY CARE COMBO (1586)', u'BANQUETS/ROOM SERVICE',
       u'1584-DAY CARE ABOVE 2 YEARS', u'FOOD PANTRY',
       u'BOYS AND GIRLS CLUB', u'DELI', u'COMMIASARY', u'TAVERN-LIQUOR',
       u'ANIMAL SHELTER CAFE PERMIT', u'DAYCARE 1586', u'NON -PROFIT',
       u'LIQUOR/COFFEE KIOSK', u'FROZEN DESSERTS DISPENSER-NON-MOTORIZED',
       u'MUSEUM/GALLERY', u'MOBILE FOOD DESSERTS VENDOR', u'TAVERN/STORE',
       u'CANDY MAKER', u'UNUSED STORAGE', u'ADULT FAMILY CARE CENTER',
       u'MOBILE DESSERT CART', u'LAUNDROMAT',
       u'POP-UP FOOD ESTABLISHMENT USER-TIER II', u'ART GALLERY',
       u'PACKAGED FOOD DISTRIBUTION', u'RELIGIOUS',
       u'NON-FOR PROFIT BASEMENT KIT', u'FURNITURE STORE',
       u'FROZEN DESSERTS DISPENSER -NON MOTORIZED', u'PRODUCE STAND',
       u'CONVENIENCE/DRUG STORE', u'DELI/GROCERY STORE',
       u'DRUG STORE/W/ FOOD', u'DELI/BAKERY',
       u'DOLLAR STORE SELLING GROCERY', u'GENERAL STORE',
       u'(CONVENIENCE STORE)', u'RETAIL STORE', u'HERBALIFE/ZUMBA',
       u'RETAIL STORE OFFERS COOKING CLASSES',
       u'ASSISTED LIVING FACILITY', u'RESTAURANT/LIQUOR', u'POPCORN CORN',
       u'HERBALIFE NUTRITION', u'BLOCKBUSTER VIDEO',
       u'TAP ROOM/TAVERN/LIQUOR STORE', u'MASSAGE BAR', u'INCUBATOR',
       u'JUICE BAR/GROCERY', u'HAIR SALON', u'COFFEE',
       u'GROCERY STORE/DELI', u'THEATER/BAR', u'PEDDLER',
       u'PACKAGED HEALTH FOODS', u'AFTER SCHOOL CARE'], dtype=object)

In [80]:
df = pd.get_dummies(df, prefix="RiskLevel",columns=['RiskLevel'])
df = pd.get_dummies(df, prefix="City",columns=['City'])
df = pd.get_dummies(df, prefix="State",columns=['State'])
df = pd.get_dummies(df, prefix="Reason",columns=['Reason'])
df = pd.get_dummies(df, prefix="SectionViolations",columns=['SectionViolations'])

In [88]:
from sklearn import preprocessing 
  
# label_encoder object knows how to understand word labels. 
label_encoder = preprocessing.LabelEncoder() 
  
# Encode labels in column 'species'. 
df['Type']= label_encoder.fit_transform(df['Type']) 
df['Geo_Loc'] = label_encoder.fit_transform(df['Geo_Loc'])

,Type,Street,LocationID,Geo_Loc,Inspection_Results,RiskLevel_High,RiskLevel_Low,RiskLevel_Medium,RiskLevel_Uncertain,City_id-11235901,...,SectionViolations_53,SectionViolations_54,SectionViolations_55,SectionViolations_56,SectionViolations_57,SectionViolations_58,SectionViolations_59,SectionViolations_60,SectionViolations_63,SectionViolations_70
0,326,15522,81876,6889,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,182,3057,81862,14998,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,326,14988,81883,9140,6,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,326,3661,81859,1991,4,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
4,326,7876,81886,2443,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
5,326,12275,81877,9758,1,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
6,326,2133,81887,15101,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
7,326,5006,81851,13704,1,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
8,75,4554,81892,642,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
9,326,5899,81877,9916,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
10,326,16017,81864,4407,6,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
11,182,4538,81867,15016,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
12,326,17881,81862,13448,3,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
13,326,14317,81905,6217,1,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
14,326,4306,81846,13903,5,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
15,162,16864,81866,8946,4,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
16,326,12997,81901,5645,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
17,326,4998,81851,12964,1,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
18,326,16901,81897,4864,5,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
19,182,13485,81885,5897,1,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
20,326,8060,81861,10555,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
21,326,17137,81902,2319,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
22,351,11623,81877,10089,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
23,297,13866,81884,1812,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
24,125,4632,81873,8136,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
25,258,17161,81852,13882,4,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
26,182,16529,81857,14988,1,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
27,326,12567,81875,5428,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
28,351,15092,81904,6527,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
29,251,11988,81854,9883,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147413,351,11623,81877,10089,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
147414,127,16773,81897,5673,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
147415,351,13261,81857,14470,5,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
147416,326,11730,81870,4667,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
147417,326,16980,81864,5013,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
147418,326,10443,81856,14370,6,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
147419,182,11277,81886,4281,1,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
147420,326,12001,81877,9847,5,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
147421,326,11595,81874,8469,1,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
147422,182,15759,81882,8080,4,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
147423,326,13766,81852,12709,3,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
147424,326,12583,81875,4986,6,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
147425,326,1196,81855,15848,1,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
147426,326,12500,81906,13387,1,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
147427,326,9431,81863,2683,6,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
147428,326,91,81854,10544,1,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
147429,326,6397,81894,7731,1,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
147430,326,5254,81855,15205,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
147431,351,9995,81863,3670,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
147432,326,130,81867,180,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
147433,274,12524,81854,9704,4,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
147434,326,11356,81870,4440,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
147435,26,11326,81886,4323,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
147436,326,16667,81865,7287,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
147437,351,1031,81873,7900,1,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
147438,182,6229,81873,7707,1,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
147439,326,3697,81848,13286,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
147440,326,13027,81877,9408,6,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
147441,326,17833,81888,13688,5,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
147442,75,7750,81904,6555,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [90]:
df.to_excel(excel_writer = "/home/ryan/stark/machinehack/Food_QUalityA_ParticipantsData/Food_QUalityA_ParticipantsData/Data_TrainCLEANEDandONEHOT.xlsx")

In [92]:
df = pd.read_excel("/home/ryan/stark/machinehack/Food_QUalityA_ParticipantsData/Food_QUalityA_ParticipantsData/Data_TrainCLEANEDandONEHOT.xlsx")

In [93]:
df

,Type,Street,LocationID,Geo_Loc,Inspection_Results,RiskLevel_High,RiskLevel_Low,RiskLevel_Medium,RiskLevel_Uncertain,City_id-11235901,...,SectionViolations_53,SectionViolations_54,SectionViolations_55,SectionViolations_56,SectionViolations_57,SectionViolations_58,SectionViolations_59,SectionViolations_60,SectionViolations_63,SectionViolations_70
0,326,15522,81876,6889,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,182,3057,81862,14998,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,326,14988,81883,9140,6,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,326,3661,81859,1991,4,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
4,326,7876,81886,2443,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
5,326,12275,81877,9758,1,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
6,326,2133,81887,15101,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
7,326,5006,81851,13704,1,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
8,75,4554,81892,642,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
9,326,5899,81877,9916,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
10,326,16017,81864,4407,6,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
11,182,4538,81867,15016,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
12,326,17881,81862,13448,3,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
13,326,14317,81905,6217,1,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
14,326,4306,81846,13903,5,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
15,162,16864,81866,8946,4,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
16,326,12997,81901,5645,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
17,326,4998,81851,12964,1,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
18,326,16901,81897,4864,5,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
19,182,13485,81885,5897,1,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
20,326,8060,81861,10555,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
21,326,17137,81902,2319,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
22,351,11623,81877,10089,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
23,297,13866,81884,1812,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
24,125,4632,81873,8136,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
25,258,17161,81852,13882,4,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
26,182,16529,81857,14988,1,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
27,326,12567,81875,5428,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
28,351,15092,81904,6527,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
29,251,11988,81854,9883,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147413,351,11623,81877,10089,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
147414,127,16773,81897,5673,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
147415,351,13261,81857,14470,5,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
147416,326,11730,81870,4667,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
147417,326,16980,81864,5013,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
147418,326,10443,81856,14370,6,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
147419,182,11277,81886,4281,1,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
147420,326,12001,81877,9847,5,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
147421,326,11595,81874,8469,1,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
147422,182,15759,81882,8080,4,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
147423,326,13766,81852,12709,3,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
147424,326,12583,81875,4986,6,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
147425,326,1196,81855,15848,1,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
147426,326,12500,81906,13387,1,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
147427,326,9431,81863,2683,6,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
147428,326,91,81854,10544,1,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
147429,326,6397,81894,7731,1,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
147430,326,5254,81855,15205,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
147431,351,9995,81863,3670,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
147432,326,130,81867,180,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
147433,274,12524,81854,9704,4,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
147434,326,11356,81870,4440,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
147435,26,11326,81886,4323,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
147436,326,16667,81865,7287,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
147437,351,1031,81873,7900,1,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
147438,182,6229,81873,7707,1,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
147439,326,3697,81848,13286,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
147440,326,13027,81877,9408,6,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
147441,326,17833,81888,13688,5,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
147442,75,7750,81904,6555,4,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0